### ISSUE TITLE
Orphan instances detection in haskell-process-trigger-suggestions is outdated

### ISSUE THREAD

**Issue by geraldus** [haskell/haskell-mode#1110]
I can't be certain, but it looks like orphan instance warning have changed in recent versions of GHC.  Currently `haskell-process-trigger-suggestions` function uses following regex to detect orphan instance warnings in compiler response `"Warning: orphan instance: "` [[1]], while GHC 7.10.3 gives a bit different formatting:

```
/Users/oman/dev/haskell/sol/solitaire/src/Solitaire.hs:12:10: Warning:
    Orphan instance: instance Show Layer
    To avoid this
        move the instance declaration to the module of the class or of the type, or
        wrap the type with a newtype and declare the instance on the new type.
```

@gracjan I know we need tests for this function, it's quite big and good test suite should rely on genuine GHC response, what will you say?

[1]:https://github.com/haskell/haskell-mode/blob/322782edfb3603911431e75d171fad9a9dfe6ff4/haskell-load.el#L153

**Comment by geraldus** [comment]
**TODO**: test other suggestions:

+ [ ] Use … to permit this
+ [ ] Use … to allow
+ [ ] Use … if you want to disable this
+ [ ] use …
+ [ ] You need
+ [ ] against inferred type [Char]
+ [ ] with actual type [Char]
+ [ ] `haskell-process-suggest-google-imports`
+ [ ] `haskell-process-suggest-haskell-docs-import`
+ [ ] `haskell-process-suggest-hayoo-imports`
+ [ ] `haskell-process-suggest-add-package`

**Comment by geraldus** [comment]
It looks like orphan instances warning was changed really long ago: https://github.com/ghc/ghc/commit/5508ada4b1d90ee54d92f69bbff7f66b3e8eceef#diff-e8ff0f7ff4e9411e2df0dba1dbd4bdd8L846

**Comment by gracjan** [comment]
We should have a test file per each warning message. Then we should run each supported GHC version with each file producing a matrix of NxM messages.

And then we need to support all of that :)

**Comment by gracjan** [comment]
@geraldus: Can you do first step, that is generate X.hs files, each generating one message of interest?

**Comment by geraldus** [comment]
@gracjan Maybe at the of week, but no promises.

**Comment by geraldus** [comment]
@gracjan I have created few files, but have no idea what to do with them :D

**Comment by gracjan** [comment]
We need a test case. Can you put them in a directory under `tests` and then create a pull request? We will make something sensible with this.

**Comment by geraldus** [comment]
Done #1168
